### ISSUE TITLE
Email verification

### ISSUE THREAD

**Issue by andreasjberg** [co-inform/Gateway#17]
The email addresses are never verified that the user controls the specified email

**Comment by davidsalvador** [comment]
To verify the email a very simple web application will be needed. A link to this web app will be sent to the user when requiring the email verification. The web app can be hosted in, for example, `https://users.co-inform.eu/confirm-email.html`.

Here is my suggestion for the email verification flow.
1. The Browser Plugin sends a registry request to the Gateway through the endpoint `POST /register`. Including the username and password.
2. The Gateway validates that the user doesn't already exist. If so, returns an error.
3. The Gateway generates 32 bytes [secure random](https://docs.oracle.com/javase/8/docs/api/java/security/SecureRandom.html) token (base64 encoded). The token, its generation date, and the assigned user is stored in the database.
4. The Gateway sends an email to the provided username (email address) with a URL following this format: `https://users.co-inform.eu/confirm-email.html#email=<email-address>&token=<token-value>`.
5. The user clicks on the URL received by email which is opened in their browser.
6. The web app retrieves the `token` and the `email` from the URL and sends it to the Gateway through the endpoint `POST /confirm-email` which includes the token and the email in the request's body.
7. The Gateway validates the received email address and token against the database. It also validates that the creation date is no older than 2 hours. If not valid or older than expected, returns an error.
8. The Gateway updates the status of the user in the database (email validated).
9. The Gateway responds with `200 OK` and the web app displays a success message.
