### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by davidsalvador** [co-inform/Gateway#20]
Here's a suggestion on how to securely implement the _Forgot Password_ flow. As in #17 , a simple web app is needed. It can be hosted, for example, in `https://users.co-inform.eu/forgot-password.html`.

The flow is the following:
1. A not logged in Browser Plugin user, clicks on "Forgot Password" providing their username (email address).
2. The Browser Plugin calls Gateway's endpoint `POST /forgot-password` providing the username in the body of the request.
3. The Gateway checks if the username exists. If not, an error is returned.
4. The Gateway generates a 32 bytes [secure random](https://docs.oracle.com/javase/8/docs/api/java/security/SecureRandom.html) token (base64 encoded). The token, its generation date, and the assigned user is stored in the database.
5. The Gateway sends an email to the provided username (email address) with a URL following this format: `https://users.co-inform.eu/forgot-password.html#email=<email-address>&token=<token-value>`.
6. The Gateway sends a `200 OK` HTTP response to the Browser Plugin.
7. The user clicks on the URL received by email which is opened in their browser.
8. The web app retrieves the `token` and the `email` from the URL. Additionally, the web app has two fields: new password and confirm new password. The user inputs the new password. Then, the web app sends the new password, the `token`, and the `email` to the Gateway through the endpoint `POST /update-password`. All the data is sent through the request's body.
9. The Gateway validates the token (that it exists in the database and it's not older than 15 minutes). and the email address. Finally, if the validations are ok the user's password is updated by the one provided.
10. The Gateway responds with 200 OK and the web app displays a success message.
11. The Gateway sends an email to the user informing that the password has been successfully updated.

Edit: Adding step 11.

**Comment by aleixac** [comment]
To also avoid the User Enumeration issue here, in the Forgot Password functionality, the 3rd point in this procedure flow should change:
- The Gateway checks if the username exists. If not, an error is returned

Should be replaced by a generic success response, either if the username (email) exists or not. But internally, the email would only be sent if the username exists.

Based on the issue: https://github.com/co-inform/Gateway/issues/22
