### ISSUE TITLE
Plugin Evaluation Logs

### ISSUE THREAD

**Issue by andreasjberg** [co-inform/Gateway#57]
Send evaluation logs for the research version to ESI. 

1. Create an basic endpoint with the following input:
     - user_id (text): Co-Inform user (ID / user mail)
     - plugin_version (text): Plugin version name
     - log_time (timestamp): Epoch UTC time of the log
     - log_category (text): One of the log categories (blurring, publish tweet, retweet, explainability, feedback, claim, ...)
     - related_item_url (text): Related Url of the Tweet (maybe other URL items also)
     - related_item_data (text): Related item extra Data (e.g.: tweet content, tweet label, new tweet text)
     - log_action (text): Log action description text (also extra information about the log action, e.g.: claim label, claim url, ...)
1. Format and populate the input
1. Send the populated and formatted object to ESI

**Comment by daffyDukk** [comment]
Need to add entries in the User DB table for

- [x] Agree to participate in research
- [x] Agree to receive communication from coinform project

and also put this information in the JWT token for the plugin.

**Comment by daffyDukk** [comment]
This is now done and deployed
